language: node_js

node_js:
  - 'v12.19.0'

cache:
  directories:
    - node_modules

install:
  - npm i -g yarn@1.22.10
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn typecheck
  - yarn build

notifications:
  email: false
