language: node_js

node_js:
- '10'

cache:
  directories:
  - node_modules

install:
- yarn install

script:
- yarn lint
- yarn test
- yarn typecheck
- yarn build

notifications:
  email: false
  webhooks: https://www.travisbuddy.com
  on_success: never
