import { CompanyProperties } from './types'

export const hedvigCompany: CompanyProperties = {
  name: 'Hedvig',
  propertyProtection: true,
  travelProtection: true,
  assaultProtection: true,
  liabilityProtection: true,
  legalProtection: true,
  drulle: true,
  trustpilotScore: 4.5,
}

export const otherCompanies: CompanyProperties[] = [
  {
    name: 'Folksam Bas',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: 'Tillval',
    trustpilotScore: 1.7,
  },
  {
    name: 'Trygg Hansa',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: 'Tillval',
    trustpilotScore: 1.7,
  },
  {
    name: 'If Hem',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: 'Tillval',
    trustpilotScore: 1.7,
  },
  {
    name: 'Ica',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: 'Tillval',
    trustpilotScore: 1.7,
  },
  {
    name: 'Länsförsäkringar',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: 'Tillval',
    trustpilotScore: 1.7,
  },
]
