import { CompanyProperties } from './types'

export const hedvigCompany: CompanyProperties = {
  name: 'Hedvig',
  propertyProtection: true,
  travelProtection: true,
  assaultProtection: true,
  liabilityProtection: true,
  legalProtection: true,
  drulle: true,
  trustpilotScore: 4.5,
}

export const otherCompanies: CompanyProperties[] = [
  {
    name: 'Folksam Bas',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.9,
  },
  {
    name: 'Trygg Hansa',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.2,
  },
  {
    name: 'If Hem',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.6,
  },
  {
    name: 'Ica',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: true,
    trustpilotScore: 3.6,
  },
  {
    name: 'Länsförsäkringar',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.6,
  },
  {
    name: 'Moderna Försäkringar Grundskydd',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.9,
  },
]
