import { CompanyProperties } from './types'

export const hedvigCompany: CompanyProperties = {
  name: 'Hedvig',
  id: 'hedvig',
  propertyProtection: true,
  travelProtection: true,
  assaultProtection: true,
  liabilityProtection: true,
  legalProtection: true,
  drulle: true,
  trustpilotScore: 4.6,
}

export const otherCompanies: CompanyProperties[] = [
  {
    name: 'Folksam Bas',
    id: 'Folksam',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.9,
  },
  {
    name: 'Trygg Hansa',
    id: 'Trygg-Hansa',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 2.2,
  },
  {
    name: 'If Hem',
    id: 'if',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 4.3,
  },
  {
    name: 'Ica',
    id: 'ICA',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: true,
    trustpilotScore: 3.3,
  },
  {
    name: 'Länsförsäkringar',
    id: 'Länsförsäkringar',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.5,
  },
  {
    name: 'Moderna Försäkringar Grundskydd',
    id: 'Moderna',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 3.5,
  },
  {
    name: 'Vardia Hemförsäkring',
    id: 'Vardia',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 1.4,
  },
  {
    name: 'Dina Försäkringar',
    id: 'Dina Försäkringar',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 2.1,
  },
  {
    name: 'Gjensidige Bas',
    id: 'Gjensidige',
    propertyProtection: true,
    travelProtection: true,
    assaultProtection: true,
    liabilityProtection: true,
    legalProtection: true,
    drulle: false,
    trustpilotScore: 2.1,
  },
]
